apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: rancher-demo
  template:
    spec:
      containers:
      - image: monachus/rancher-demo:latest
        name: rancher-demo
        envFrom:
        - configMapRef:
            name: rancher-demo-config
