apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rancher-demo
resources:
- configs/source-vars.yaml
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
configMapGenerator:
- name: rancher-demo-config
  env: configs/env.txt
images:
- name: monachus/rancher-demo
  newName: monachus/rancher-demo
  newTag: latest
commonLabels:
  app.kubernetes.io/name: rancher-demo
vars:
- fieldref:
    fieldPath: data.MY_NAMESPACE
  name: MY_NAMESPACE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: source-vars
- fieldref:
    fieldPath: data.URL_HOST
  name: URL_HOST
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: source-vars
configurations:
- kustomize-config.yaml

